"""initial

Revision ID: b1962acb4489
Revises: 
Create Date: 2026-09-14 18:11:55.464007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b1962acb4489'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('subscription_plan', sa.String(length=20), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_verification_codes',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Enum('register', 'login', name='verificationpurpose'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_verification_codes_phone'), 'phone_verification_codes', ['phone'], unique=False)
    op.create_table('reminders',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('rto_deadline', 'etrn_deadline', 'vehicle_inspection', 'custom', name='remindertype'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('starter', 'pro', 'fleet', name='subscriptionplan'), nullable=False),
    sa.Column('vehicles_limit', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'trial', 'expired', name='subscriptionstatus'), nullable=False),
    sa.Column('yookassa_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'dispatcher', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vehicles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('brand_model', sa.String(length=255), nullable=False),
    sa.Column('tachograph_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'repair', 'inactive', name='vehiclestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_location', sa.String(length=255), nullable=True),
    sa.Column('end_location', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', name='tripstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rto_violations',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('violation_type', sa.Enum('daily_driving_exceeded', 'continuous_driving_exceeded', 'daily_rest_insufficient', 'weekly_rest_insufficient', 'biweekly_driving_exceeded', name='violationtype'), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'violation', name='violationseverity'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waybills',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('pdf_file_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', name='waybillstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_time_entries',
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('driving', 'rest', 'other_work', 'availability', name='entrytype'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('manual', 'import_file', name='entrysource'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_time_entries')
    op.drop_table('waybills')
    op.drop_table('rto_violations')
    op.drop_table('trips')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_phone_verification_codes_phone'), table_name='phone_verification_codes')
    op.drop_table('phone_verification_codes')
    op.drop_table('drivers')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    # op.drop_table() не удаляет типы Postgres ENUM, привязанные к колонкам
    # (известное ограничение Alembic) — удаляем их явно, иначе повторный
    # upgrade падает с "type ... already exists".
    bind = op.get_bind()
    for enum_name in (
        "entrysource",
        "entrytype",
        "remindertype",
        "subscriptionplan",
        "subscriptionstatus",
        "tripstatus",
        "userrole",
        "vehiclestatus",
        "verificationpurpose",
        "violationseverity",
        "violationtype",
        "waybillstatus",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
